version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:16
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    working_directory: ~/project

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Print Docker Version
          command: docker --version
      - run:
          name: Build Docker Images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t reverseproxy ./udagram-reverseproxy
      - run:
          name: Tag Docker Images
          command: |
            docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
            docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
            docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1
            docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v1
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Images to DockerHub
          command: |
            docker push $DOCKER_USERNAME/udagram-api-feed:v1
            docker push $DOCKER_USERNAME/udagram-api-user:v1
            docker push $DOCKER_USERNAME/udagram-frontend:v1
            docker push $DOCKER_USERNAME/reverseproxy:v1

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push
