version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable  # Đây là image chính để chạy các lệnh trong môi trường CircleCI
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          # Bỏ qua việc chỉ định version ở đây
      - run:
          name: Build udagram-api-user image
          command: |
            docker build \
              --build-arg POSTGRES_USERNAME=$POSTGRES_USERNAME \
              --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
              --build-arg POSTGRES_HOST=$POSTGRES_HOST \
              --build-arg POSTGRES_DB=$POSTGRES_DB \
              --build-arg AWS_REGION=$AWS_REGION \
              --build-arg AWS_PROFILE=$AWS_PROFILE \
              --build-arg AWS_BUCKET=$AWS_BUCKET \
              --build-arg JWT_SECRET=$JWT_SECRET \
              -t $DOCKERHUB_USERNAME/udagram-api-user:latest ./udagram-api-user
      - run:
          name: Build udagram-api-feed image
          command: |
            docker build \
              --build-arg POSTGRES_USERNAME=$POSTGRES_USERNAME \
              --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
              --build-arg POSTGRES_HOST=$POSTGRES_HOST \
              --build-arg POSTGRES_DB=$POSTGRES_DB \
              --build-arg AWS_REGION=$AWS_REGION \
              --build-arg AWS_PROFILE=$AWS_PROFILE \
              --build-arg AWS_BUCKET=$AWS_BUCKET \
              --build-arg JWT_SECRET=$JWT_SECRET \
              -t $DOCKERHUB_USERNAME/udagram-api-feed:latest ./udagram-api-feed
      - run:
          name: Build udagram-frontend image
          command: |
            docker build -t $DOCKERHUB_USERNAME/udagram-frontend:latest ./udagram-frontend
      - run:
          name: Build udagram-reverseproxy image
          command: |
            docker build -t $DOCKERHUB_USERNAME/udagram-reverseproxy:latest ./udagram-reverseproxy

  push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          # Không cần chỉ định phiên bản Docker nữa
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push udagram-api-user image
          command: |
            docker push $DOCKERHUB_USERNAME/udagram-api-user:latest
      - run:
          name: Push udagram-api-feed image
          command: |
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest
      - run:
          name: Push udagram-frontend image
          command: |
            docker push $DOCKERHUB_USERNAME/udagram-frontend:latest
      - run:
          name: Push udagram-reverseproxy image
          command: |
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
