version: 2.1

orbs:
  node: circleci/node@5.0
  docker: circleci/docker@2.1.0

executors:
  docker-executor:
    docker:
      - image: cimg/docker:20.10
    working_directory: ~/repo

jobs:
  build-frontend:
    executor: docker-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build frontend
          command: |
            cd udagram-frontend
            npm run build
      - run:
          name: Build Docker image for frontend
          command: |
            docker build -t $DOCKER_USERNAME/udagram-frontend:latest ./udagram-frontend
      - run:
          name: Push frontend Docker image to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/udagram-frontend:latest

  build-backend-user:
    executor: docker-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Docker image for backend user
          command: |
            docker build -t $DOCKER_USERNAME/udagram-api-user:latest ./udagram-api-user
      - run:
          name: Push backend user Docker image to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/udagram-api-user:latest

  build-backend-feed:
    executor: docker-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Docker image for backend feed
          command: |
            docker build -t $DOCKER_USERNAME/udagram-api-feed:latest ./udagram-api-feed
      - run:
          name: Push backend feed Docker image to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/udagram-api-feed:latest

  build-reverseproxy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build Docker image for reverseproxy
          command: |
            docker build -t $DOCKER_USERNAME/reverseproxy:latest ./udagram-reverseproxy
      - run:
          name: Push reverseproxy Docker image to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/reverseproxy:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-frontend
      - build-backend-user:
          requires:
            - build-frontend
      - build-backend-feed:
          requires:
            - build-backend-user
      - build-reverseproxy:
          requires:
            - build-backend-feed
