version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker images
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t lin929/reverseproxy:${CIRCLE_SHA1} ./udagram-reverseproxy
            docker build -t lin929/udagram-api-user:${CIRCLE_SHA1} ./udagram-api-user
            docker build -t lin929/udagram-api-feed:${CIRCLE_SHA1} ./udagram-api-feed
            docker build -t lin929/udagram-frontend:${CIRCLE_SHA1} ./udagram-frontend
            docker push lin929/reverseproxy:${CIRCLE_SHA1}
            docker push lin929/udagram-api-user:${CIRCLE_SHA1}
            docker push lin929/udagram-api-feed:${CIRCLE_SHA1}
            docker push lin929/udagram-frontend:${CIRCLE_SHA1}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          context: docker-hub-creds